platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# FIX: ambil flutter_root dari ENV CI
flutter_root = ENV['FLUTTER_ROOT']
raise "FLUTTER_ROOT not set" if flutter_root.nil? or flutter_root.empty?

load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
